import Head from "next/head";
import {
  Dispatch,
  SetStateAction,
  createContext,
  useEffect,
  useState,
} from "react";
import Home from "./home";
import { OptionRadioProps } from "@/shared/types/OptionRadioProps";

interface ContextProps {
  favoriteRadioList: Array<OptionRadioProps>;
  setFavoriteRadioList: Dispatch<SetStateAction<Array<OptionRadioProps>>>;

  urlRadioPlaying: string;
  setUrlRadioPlaying: Dispatch<SetStateAction<string>>;

  radioNamePlaying: string;
  setRadioNamePlaying: Dispatch<SetStateAction<string>>;

  menuActive: boolean;
  setMenuActive: Dispatch<SetStateAction<boolean>>;

  searchingRadio: string;
  setSearchingRadio: Dispatch<SetStateAction<string>>;
}

export const Context = createContext<ContextProps>({
  favoriteRadioList: [],
  setFavoriteRadioList: () => {},

  menuActive: false,
  setMenuActive: () => {},

  radioNamePlaying: "",
  setRadioNamePlaying: () => {},

  urlRadioPlaying: "",
  setUrlRadioPlaying: () => {},

  searchingRadio: "",
  setSearchingRadio: () => {},
});

export default function Index() {
  const [menuActive, setMenuActive] = useState(false);
  const [urlRadioPlaying, setUrlRadioPlaying] = useState(
    "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_89FM_ADP.aac?dist=site-89fm"
  );

  const [radioNamePlaying, setRadioNamePlaying] = useState(
    "Rádio Rock - 89,1 FM"
  );

  const [favoriteRadioList, setFavoriteRadioList] = useState<
    OptionRadioProps[]
  >([]);

  const [searchingRadio, setSearchingRadio] = useState("");

  useEffect(() => {
    const storedFavorites = localStorage.getItem("favoriteRadioList");
    const parsedFavorites = storedFavorites ? JSON.parse(storedFavorites) : [];

    setFavoriteRadioList(parsedFavorites);
  }, []);

  return (
    <Context.Provider
      value={{
        menuActive,
        setMenuActive,
        urlRadioPlaying,
        setUrlRadioPlaying,
        radioNamePlaying,
        setRadioNamePlaying,
        favoriteRadioList,
        setFavoriteRadioList,
        searchingRadio,
        setSearchingRadio,
      }}
    >
      <Head>
        <title>Radio Browser Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home />
      </main>
    </Context.Provider>
  );
}
